// // property.dart

// Ensure this file is in a valid Dart/Flutter project, e.g., lib/models/property.dart or lib/data/dummy_data.dart

// Import necessary libraries (adjust based on your project structure)

// Define the Property model

// Dummy data for testing


// class Property {
//   final String id;
//   final String title;
//   final String location;
//   final double rating;
//   final double price;
//   final double totalPrice;
//   final List<String> images;
//   final String category;
//   final bool isGuestFavorite;
//   final bool hasMap;
//   final String distanceDescription;
//   final String availabilityDescription;

//   Property({
//     required this.id,
//     required this.title,
//     required this.location,
//     required this.rating,
//     required this.price,
//     required this.totalPrice,
//     required this.images,
//     required this.category,
//     required this.isGuestFavorite,
//     required this.hasMap,
//     required this.distanceDescription,
//     required this.availabilityDescription,
//   });
// }

// // Service to handle property data
// class PropertiesService {
//   Future<List<Property>> getProperties() async {
//     // TODO: Implement actual data fetching logic
//     // This is a placeholder that returns an empty list
//     return [];
//   }
// }
// final dummyProperties = [
//   // Cars (6 items)
//   Property(
//     id: 'car1',
//     title: 'Sporty Car',
//     location: 'Mumbai, India',
//     rating: 4.5,
//     price: 2000,
//     totalPrice: 2500,
//     images: ['assets/car1.png'],
//     category: 'Cars',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '10 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'car2',
//     title: 'Luxury Sedan',
//     location: 'Delhi, India',
//     rating: 4.8,
//     price: 3000,
//     totalPrice: 3500,
//     images: ['assets/car2.png'],
//     category: 'Cars',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '15 km away',
//     availabilityDescription: 'Available tomorrow',
//   ),
//   Property(
//     id: 'car3',
//     title: 'Convertible',
//     location: 'Bangalore, India',
//     rating: 4.6,
//     price: 2500,
//     totalPrice: 3000,
//     images: ['assets/car3.png'],
//     category: 'Cars',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: '20 km away',
//     availabilityDescription: 'Available next week',
//   ),
//   Property(
//     id: 'car4',
//     title: 'Compact Car',
//     location: 'Hyderabad, India',
//     rating: 4.2,
//     price: 1800,
//     totalPrice: 2200,
//     images: ['assets/car4.png'],
//     category: 'Cars',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '5 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'car5',
//     title: 'Family SUV',
//     location: 'Chennai, India',
//     rating: 4.7,
//     price: 2800,
//     totalPrice: 3300,
//     images: ['assets/car5.png'],
//     category: 'Cars',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: '8 km away',
//     availabilityDescription: 'Available this weekend',
//   ),
//   Property(
//     id: 'car6',
//     title: 'Vintage Classic',
//     location: 'Kolkata, India',
//     rating: 4.4,
//     price: 2200,
//     totalPrice: 2700,
//     images: ['assets/car6.png'],
//     category: 'Cars',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '12 km away',
//     availabilityDescription: 'Available soon',
//   ),

//   // Bikes (6 items)
//   Property(
//     id: 'bike1',
//     title: 'Sports Bike',
//     location: 'Mumbai, India',
//     rating: 4.5,
//     price: 1500,
//     totalPrice: 1800,
//     images: ['assets/bike1.png'],
//     category: 'Bikes',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '8 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'bike2',
//     title: 'Cruiser Bike',
//     location: 'Delhi, India',
//     rating: 4.7,
//     price: 1600,
//     totalPrice: 1900,
//     images: ['assets/bike2.png'],
//     category: 'Bikes',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: '12 km away',
//     availabilityDescription: 'Available tomorrow',
//   ),
//   Property(
//     id: 'bike3',
//     title: 'Electric Bike',
//     location: 'Bangalore, India',
//     rating: 4.8,
//     price: 1700,
//     totalPrice: 2000,
//     images: ['assets/bike3.png'],
//     category: 'Bikes',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '10 km away',
//     availabilityDescription: 'Available next week',
//   ),
//   Property(
//     id: 'bike4',
//     title: 'Classic Bike',
//     location: 'Hyderabad, India',
//     rating: 4.3,
//     price: 1400,
//     totalPrice: 1700,
//     images: ['assets/bike4.png'],
//     category: 'Bikes',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '6 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'bike5',
//     title: 'Adventure Bike',
//     location: 'Chennai, India',
//     rating: 4.6,
//     price: 1550,
//     totalPrice: 1850,
//     images: ['assets/bike5.png'],
//     category: 'Bikes',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: '9 km away',
//     availabilityDescription: 'Available this weekend',
//   ),
//   Property(
//     id: 'bike6',
//     title: 'Touring Bike',
//     location: 'Kolkata, India',
//     rating: 4.4,
//     price: 1500,
//     totalPrice: 1800,
//     images: ['assets/bike6.png'],
//     category: 'Bikes',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '11 km away',
//     availabilityDescription: 'Available soon',
//   ),

//   // Laptops (6 items)
//   Property(
//     id: 'laptop1',
//     title: 'Gaming Laptop',
//     location: 'Mumbai, India',
//     rating: 4.9,
//     price: 80000,
//     totalPrice: 85000,
//     images: ['assets/laptop1.png'],
//     category: 'Laptops',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'In stock',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'laptop2',
//     title: 'Ultrabook',
//     location: 'Delhi, India',
//     rating: 4.8,
//     price: 75000,
//     totalPrice: 80000,
//     images: ['assets/laptop2.png'],
//     category: 'Laptops',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'In stock',
//     availabilityDescription: 'Available today',
//   ),
//   Property(
//     id: 'laptop3',
//     title: 'Business Laptop',
//     location: 'Bangalore, India',
//     rating: 4.7,
//     price: 70000,
//     totalPrice: 75000,
//     images: ['assets/laptop3.png'],
//     category: 'Laptops',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'In stock',
//     availabilityDescription: 'Available tomorrow',
//   ),
//   Property(
//     id: 'laptop4',
//     title: 'Convertible Laptop',
//     location: 'Hyderabad, India',
//     rating: 4.6,
//     price: 68000,
//     totalPrice: 73000,
//     images: ['assets/laptop4.png'],
//     category: 'Laptops',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'In stock',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'laptop5',
//     title: '2-in-1 Laptop',
//     location: 'Chennai, India',
//     rating: 4.8,
//     price: 72000,
//     totalPrice: 77000,
//     images: ['assets/laptop5.png'],
//     category: 'Laptops',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'In stock',
//     availabilityDescription: 'Available this weekend',
//   ),
//   Property(
//     id: 'laptop6',
//     title: 'Budget Laptop',
//     location: 'Kolkata, India',
//     rating: 4.5,
//     price: 60000,
//     totalPrice: 65000,
//     images: ['assets/laptop6.png'],
//     category: 'Laptops',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'In stock',
//     availabilityDescription: 'Available soon',
//   ),

//   // Cameras (6 items)
//   Property(
//     id: 'camera1',
//     title: 'DSLR Camera',
//     location: 'Mumbai, India',
//     rating: 4.9,
//     price: 45000,
//     totalPrice: 48000,
//     images: ['assets/camera1.png'],
//     category: 'Cameras',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'In store',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'camera2',
//     title: 'Mirrorless Camera',
//     location: 'Delhi, India',
//     rating: 4.8,
//     price: 50000,
//     totalPrice: 53000,
//     images: ['assets/camera2.png'],
//     category: 'Cameras',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'In store',
//     availabilityDescription: 'Available today',
//   ),
//   Property(
//     id: 'camera3',
//     title: 'Compact Camera',
//     location: 'Bangalore, India',
//     rating: 4.7,
//     price: 35000,
//     totalPrice: 38000,
//     images: ['assets/camera3.png'],
//     category: 'Cameras',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'In store',
//     availabilityDescription: 'Available tomorrow',
//   ),
//   Property(
//     id: 'camera4',
//     title: 'Action Camera',
//     location: 'Hyderabad, India',
//     rating: 4.6,
//     price: 30000,
//     totalPrice: 33000,
//     images: ['assets/camera4.png'],
//     category: 'Cameras',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'In store',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'camera5',
//     title: 'Film Camera',
//     location: 'Chennai, India',
//     rating: 4.5,
//     price: 28000,
//     totalPrice: 31000,
//     images: ['assets/camera5.png'],
//     category: 'Cameras',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'In store',
//     availabilityDescription: 'Available this weekend',
//   ),
//   Property(
//     id: 'camera6',
//     title: 'Point & Shoot',
//     location: 'Kolkata, India',
//     rating: 4.4,
//     price: 22000,
//     totalPrice: 25000,
//     images: ['assets/camera6.png'],
//     category: 'Cameras',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'In store',
//     availabilityDescription: 'Available soon',
//   ),

//   // Houses (6 items)
//   Property(
//     id: 'house1',
//     title: 'Modern Farm House',
//     location: 'Coimbatore, India',
//     rating: 4.9,
//     price: 1836,
//     totalPrice: 2500,
//     images: ['assets/house1.png'],
//     category: 'Houses',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: '259 km away',
//     availabilityDescription: '5-9 Apr',
//   ),
//   Property(
//     id: 'house2',
//     title: 'Beachfront Villa',
//     location: 'Goa, India',
//     rating: 4.8,
//     price: 2549,
//     totalPrice: 3200,
//     images: ['assets/house2.png'],
//     category: 'Houses',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '200 km away',
//     availabilityDescription: '10-15 Apr',
//   ),
//   Property(
//     id: 'house3',
//     title: 'Mountain Cabin',
//     location: 'Himalayas, India',
//     rating: 4.7,
//     price: 1899,
//     totalPrice: 2600,
//     images: ['assets/house3.png'],
//     category: 'Houses',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: '300 km away',
//     availabilityDescription: '15-20 Apr',
//   ),
//   Property(
//     id: 'house4',
//     title: 'Luxury Apartment',
//     location: 'Mumbai, India',
//     rating: 4.9,
//     price: 3249,
//     totalPrice: 4000,
//     images: ['assets/house4.png'],
//     category: 'Houses',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '5 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'house5',
//     title: 'Urban Condo',
//     location: 'Bangalore, India',
//     rating: 4.6,
//     price: 2900,
//     totalPrice: 3500,
//     images: ['assets/house5.png'],
//     category: 'Houses',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '3 km away',
//     availabilityDescription: 'Available today',
//   ),
//   Property(
//     id: 'house6',
//     title: 'Suburban Home',
//     location: 'Chennai, India',
//     rating: 4.5,
//     price: 2100,
//     totalPrice: 2700,
//     images: ['assets/house6.png'],
//     category: 'Houses',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: '8 km away',
//     availabilityDescription: 'Available this weekend',
//   ),
// ];
